#!/bin/bash
#
# NAME
#	Compare - compare TAXTools and TAXToolsDev
#
# SYNOPSIS
#	Compare 
#
###############################################################################
$DBG_SH
CMDNAME=$(basename $0)
USAGE="Usage: $CMDNAME"

if [ $# -ne 0 ]; then
	echo "$USAGE" 1>&2
	exit 1
fi

cd "$TAXTOOLS/.."
DirCmp "TAXToolsNew" "TAXToolsDev"		|
	grep -v "~"							|
	grep -v ".docx$"					|
	grep -v ".swp$"						|
	grep -v "eslint.comfig.mjs$"		|
	grep -v ".gitignore$"				|
	grep -v "package.json$"				|
	grep -v "package-lock.json$"		|
	grep -v ".git/"						|
	grep -v "_notes/"					|
	grep -v "AI-Version/"				|
	grep -v "EITC/"						|
	grep -v "EstimatedTax-Excel/"		|
	grep -v "nodes_modules/"			|
	grep -v "Tools/"					|
	grep -v "Tests/"					|
	cat -
exit
