#!/bin/bash
#
# NAME
#	createFormHTML
#
# SYNOPSIS
#	createFormHTML formname [index]
#
# DESCRIPTION
#	This command will ...
#
###############################################################################
$DBG_SH
CMDNAME=$(basename $0)
USAGE="Usage: $CMDNAME formname [index]"
SRCDIR="$TT/Library/Forms-HTML"
FIELD_FILE=
LINENUM=
LABEL=
ID=
FORM_TITLE=
FORM_NAME=
INDEX=0

CamelToEnglish() {
	# Preserve acronyms and consecutive capitals.
	RESULT="$1"
	RESULT=$(echo "$RESULT" | sed -E 's/([a-z0-9]+)([A-Z])/\1 \2/g')
	RESULT=$(echo "$RESULT" | sed -E 's/([A-Z]+)([A-Z][a-z])/\1 \2/g')
	RESULT=$(echo "$RESULT" | sed -E 's/([A-Za-z]+)([0-9])/\1 \2/g')
	RESULT=$(echo "$RESULT" | sed -E 's/([0-9]+)([A-Za-z])/\1 \2/g')
	echo "${RESULT^}"
}

if [ $# -gt 2 ]; then
	echo "$USAGE" 1>&2
	exit 1
fi
FIELD_FILE="$SRCDIR/$1-fields.txt"
if [ $# -gt 1 ]; then
	INDEX=$2
fi

if [ ! -f "$FIELD_FILE" ]; then
	echo "$CMDNAME: File \"$FIELD_FILE\" not found." 1>&2
	exit 1
fi

FORM_TITLE=$(cat $FIELD_FILE | grep -i "FORMTITLE" | sed 's/FORMTITLE//')
FORM_TITLE=$(echo $FORM_TITLE)	# Normalize spaces.
if [ "$FORM_TITLE" == "" ]; then
	echo "$CMDNAME: Form title not found." 1>&2
	exit 1
fi
FORM_NAME=$(cat $FIELD_FILE | grep -i "FORMNAME" | sed 's/FORMNAME//')
FORM_NAME=$(echo $FORM_NAME)	# Normalize spaces.
if [ "$FORM_NAME" == "" ]; then
	echo "$CMDNAME: Form name not found." 1>&2
	exit 1
fi

echo '<html lang="en">'
echo '	<details class="tax-form-container">'
echo '		<summary class="taxform-summary">'$FORM_TITLE'</summary>'
echo '		<div>'

cat $FIELD_FILE |
	while read LINENUM LABEL
	do
		if [ "$LINENUM" == "FORMNAME" ]; then
			continue
		fi
		if [ "$LINENUM" == "FORMTITLE" ]; then
			continue
		fi
		ID="$FORM_NAME-$INDEX-$LABEL"
		echo '			<div class="taxform-line trigger" tooltipid="#'$ID'TT">'
		echo '				<p>Line '$LINENUM'</p>'
		echo '				<p>'$(CamelToEnglish $LABEL)'</p>'
		echo '				<input class="input-field" type="text" id="'$ID'" size="10" placeholder="0" />'
		echo '			</div>'
	done

echo '			<p>&nbsp;</p>'
echo '		</div>'
echo '	</details>'
echo '</html>'
