#!/bin/bash
#
# NAME
#	getFields formName
#
# SYNOPSIS
#	getFields formName
#
# DESCRIPTION
#	Read the file .../Forms/formName.js and find the definition for the FIELDS.
#	If found, parse the definition and print the names of all the fields on the
#	form.
#
# EXAMPLE
#	$ cd $TT/Library/Forms
#	$ getFields W2
#
###############################################################################
$DBG_SH
CMDNAME=$(basename $0)
USAGE="Usage: $CMDNAME formname"
SRCDIR="$TT/Library/Forms"
SRCFILE=
FORMNAME=
SPACE=" "
TAB="	"

if [ $# -ne 1 ]; then
	echo "$USAGE" 1>&2
	exit 1
fi
FORMNAME="$1"

SRCFILE="$SRCDIR/$FORMNAME.js"
if [ ! -f "$SRCFILE" ]; then
	echo "$CMDNAME: File \"$FIELD_FILE\" not found." 1>&2
	exit 1
fi

START="const FIELDS"
STOP="];"
cat $SRCFILE						|
	sed "/^$START/,/^$STOP/!d"		|
	grep -E -v "^$START|^$STOP"		|
	sed "s/\/\/.*//"				|
	sed "s/\"//g"					|
	sed "s/,//g"					|
	sed "s/\[//g"					|
	sed "s/]//g"					|
	awk '{print $1 "	" $2}'			|
	cat -

exit
	sed 's/^[^,]*,//'				|
	sed "/^[$SPACE$TAB]*\$/d"		|
