#!/bin/bash
#
# NAME
#	UpdateRelease - Copy release files from TaxToolsDev too TaxToolsNew
#
# SYNOPSIS
#	UpdateRelease
#
###############################################################################
$DBG_SH
CMDNAME=$(basename $0)
USAGE="Usage: $CMDNAME"
BRANCH=
TOP=
SRCDIR=
DSTDIR=
ERRMSG=/tmp/errmsg.$$	# Error messages from cpio.

trap 'rm -f /tmp/*.$$' EXIT

if [ $# -ne 0 ]; then
	echo "$USAGE" 1>&2
	exit 1
fi

cd "$TAXTOOLS/.."
TOP=$(pwd)
SRCDIR="$TOP/TaxToolsDev"
DSTDIR="$TOP/TaxToolsNew"

cd $SRCDIR
BRANCH=$(git branch --show-current)
if [ "$BRANCH" != "main" ]; then
	echo "$CMDNAME: The TaxToolsDev directory must be in the \"main\" branch."
	exit 1
fi

if [ ! -d "$SRCDIR" ]; then
	echo "$SRCDIR is not a directory." 1>&2
	exit 1
fi

if [ ! -d "$DSTDIR" ]; then
	mkdir -p "$DSTDIR"
	if [ $? -ne 0 ]; then
		echo "$CMDNAME: Cannot create $DSTDIR" 1>&2
		exit 1
	fi
fi

cd $SRCDIR
find . -depth -print				| 
	grep -v "\/~"				|
	grep -v "\.docx"\$			|
	grep -v "\.swp"\$			|
	grep -v '/eslint.comfig.mjs'\$		|
	grep -v '/.gitignore'\$			|
	grep -v '/package.json'\$		|
	grep -v '/package-lock.json'\$		|
	grep -v '/.git'\$			|
	grep -v '/.git/'			|
	grep -v '/_notes'\$			|
	grep -v '/_notes/'			|
	grep -v '/AI-Version'\$			|
	grep -v '/AI-Version/'			|
	grep -v '/EITC'\$			|
	grep -v '/EITC/'			|
	grep -v '/EstimatedTax-Excel'\$		|
	grep -v '/EstimatedTax-Excel/'		|
	grep -v '/nodes_modules'\$		|
	grep -v '/nodes_modules/'		|
	grep -v '/Tools'\$			|
	grep -v '/Tools/'			|
	grep -v '/Tests'\$			|
	grep -v '/Tests/'			|
	cpio -pdmu $DSTDIR 2>$ERRMSG
if [ $? -ne 0 ]; then
	cat $ERRMSG 1>&2
	exit 1
fi
